---
project:
  title: My project
  description: Title of my project
  version: 1.0
  rapydo: 0.5.6

variables:
  env:
    GRAPHDB_PASSWORD: chooseapassword
    IRODS_CHUNKSIZE: 1048576
  backend:
    credentials:
      username: "user@nomail.org"
      password: "test"
      roles:
        user: normal_user
        internal: staff_user
        admin: admin_root
        default: normal_user
  frontend:
    enable: true
