---
project:
  title: My project
  description: Title of my project
  version: "RAPyDo framework v0.5.2-beta"

variables:
  repos:
    utils:
      branch: 0.5.3
    backend:
      branch: 0.5.3
    build-templates:
      branch: 0.5.3
  env:
    GRAPHDB_PASSWORD: chooseapassword
    IRODS_CHUNKSIZE: 1048576
  backend:
    credentials:
      username: "user@nomail.org"
      password: "test"
      roles:
        user: normal_user
        internal: staff_user
        admin: admin_root
        default: normal_user
  frontend:
    enable: true

